### ISSUE TITLE
TensorFlow verison problem

### ISSUE THREAD

**Issue by caomaocao** [BUPTLdy/Sentiment-Analysis#4]
Hi:
    I installed TensorFlow 1.0 as Keras engine, but got error 'TypeError: Expected int32, got...' . Then I changed TensorFlow to 0.12, the program runs well. So, I suggest you could add TensorFlow version in README. Coz there is no TensorFlow version information in requirement.txt.

**Comment by BUPTLdy** [comment]
@caomaocao Thanks for your advice, but this code use Theano as the backend, and the Theano version is (0.8.2). I will update the theano version in readme.
