### ISSUE TITLE
请问一下tensorflow 使用的版本是多少？

### ISSUE THREAD

**Issue by dyan33** [BUPTLdy/Sentiment-Analysis#5]
我安装的是tensorflow (1.1.0)，在使用lstm_predict(string)函数时会报如下错误，大致判断是tensorflow 版本问题
![image](https://cloud.githubusercontent.com/assets/8637257/26097913/bd44d00c-3a58-11e7-8c44-b2a92a9e4927.png)

**Comment by BUPTLdy** [comment]
#4 参考这个问题

**Comment by dyan33** [comment]
谢谢大佬
